CREATE DATABASE IF NOT EXISTS jira_db;
USE jira_db;

-- -------- JSM TABLE --------
CREATE TABLE IF NOT EXISTS jsm_open_issues (
  issuekey VARCHAR(20) PRIMARY KEY,
  issuetype VARCHAR(50),
  unit VARCHAR(100),
  application VARCHAR(100),
  status VARCHAR(50),
  priority VARCHAR(50),
  summary TEXT,
  summary_details TEXT,
  assignee VARCHAR(100),
  created DATETIME,
  resolved DATETIME,
  updated DATETIME,
  site_location VARCHAR(100),
  geography VARCHAR(100),
  country VARCHAR(100),
  infra_app VARCHAR(100),
  affected_ci VARCHAR(100),
  issue_category VARCHAR(100),
  owner_name VARCHAR(100),
  time_spent_seconds BIGINT,
  assigned_date_bot DATETIME,
  escalation_date_l2 DATETIME,
  assigned_date_l2 DATETIME,
  escalation_date_l3 DATETIME,
  sop_id VARCHAR(100),
  security_incident_comment TEXT,
  fault_attribution VARCHAR(100),
  closure_code VARCHAR(100),
  resolved_by_team VARCHAR(100),
  assigned_back_l1 VARCHAR(10),
  assigned_back_l2 VARCHAR(10),
  last_level_assignee VARCHAR(100),
  source VARCHAR(100),
  call_summary TEXT,
  response_sla VARCHAR(100),
  resolution_sla VARCHAR(100),
  reason_missed_response_sla VARCHAR(255),
  reason_missed_resolution_sla VARCHAR(255),
  expected_response DATETIME,
  expected_resolution DATETIME,
  services VARCHAR(255),
  service_impact VARCHAR(100),
  last_refreshed_at DATETIME
);

-- -------- JIRA TABLE --------
CREATE TABLE IF NOT EXISTS jira_open_issues (
  issuekey VARCHAR(20) PRIMARY KEY,
  summary TEXT,
  status VARCHAR(50),
  assignee VARCHAR(100),
  reporter VARCHAR(100),
  created DATETIME,
  updated DATETIME,
  issuetype VARCHAR(50),
  brief_description TEXT,
  incident_source VARCHAR(100),
  country VARCHAR(100),
  unit VARCHAR(100),
  affected_ci VARCHAR(100),
  infra_app VARCHAR(100),
  owner_name VARCHAR(100),
  incident_geography VARCHAR(100),
  application_name VARCHAR(100),
  incident_priority VARCHAR(100),
  incident_assigned_to VARCHAR(100),
  site_location VARCHAR(100),
  call_summary TEXT,
  jsm_key VARCHAR(20),
  response_sla VARCHAR(100),
  resolution_sla VARCHAR(100),
  services VARCHAR(255),
  category VARCHAR(100),
  security_incident VARCHAR(100),
  comments TEXT,
  fault_attribution VARCHAR(100),
  closure_code VARCHAR(100),
  resolved_by VARCHAR(100),
  reason_missed_resolution_sla VARCHAR(255),
  resources VARCHAR(255),
  resolution_completion_date DATETIME,
  task_type VARCHAR(100),
  task_sub_type VARCHAR(100),
  request_type VARCHAR(100),
  product_variants VARCHAR(255),
  customers VARCHAR(255),
  priority VARCHAR(50),
  bug_type VARCHAR(100),
  resolution_details TEXT,
  bug_reason VARCHAR(100),
  response_sla_bug VARCHAR(100),
  resolution_sla_bug VARCHAR(100),
  reported_by VARCHAR(100),
  resolved DATETIME,
  rca TEXT,
  capa TEXT,
  known_issue VARCHAR(100),
  five_why TEXT,
  validator_approved VARCHAR(50),
  last_refreshed_at DATETIME
);
